# Generated by Django 6.0.1 on 2026-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
