# Generated by Django 6.0.1 on 2026-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_last_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='billing_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='monthly_cost',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
